### PR TITLE
Update chapter4.txt

### PR DESCRIPTION
**Pull request by OleksiiMorozDev**
I changed existing line and added one extra line to make text more fullable.

### CODE REVIEW

**Comment by OleksiiMorozDev** [comment]
Please answer me.

**Comment by blackswift1992** [comment]
Hello

**Review by blackswift1992 — COMMENTED** [review]
Great job!

**Comment by OleksiiMorozDev** [comment]
Thank you!

**Review by blackswift1992 — APPROVED** [review]

**Pull request merged**
